version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/build
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "setup.py" }}
          - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install .[dev] codacy-coverage
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "setup.py" }}
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest --cov=openbci_interface --cov-report xml:coverage.xml tests 
            flake8 openbci_interface
            python-codacy-coverage -r coverage.xml

workflows:
  version: 2
  test:
    jobs:
      - test
